name: Push to S3
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu:latest
    steps:
    

      - name: Create S3 Bucket
        run: aws s3api create-bucket --bucket experiment-task000 --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy to S3
        run: |
         aws s3 sync . "s3://$S3_BUCKET"
         

      - name: Add public IP to AWS security group for Web App
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: 'sg-07235332c795bfc6d'
          port: '22'
          to-port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'
        
