name: Push to S3
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    

      - name: Create S3 Bucket
        run: aws s3api create-bucket --bucket experiment-task000 --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy to S3

        run: |
         S3_BUCKET="exp-task000"
         aws s3 sync . "s3://$S3_BUCKET"


        
