name: Push to S3
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
        
      - name: Add public IP to AWS security group for Web App
        uses: actions/checkout@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: 'sg-07235332c795bfc6d'
          port: '22'
          to-port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'

      - name: Create S3 Bucket
        run: aws s3api create-bucket --bucket experiment-task2 --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy index.html to S3
        run: |
          S3_BUCKET="experiment-task2"
          aws s3 cp index.html "s3://$S3_BUCKET/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
